labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: invalid
    color: e4e669
    description: Something's wrong
  - name: question
    color: d876e3
    description: Further information is requested
  - name: wontfix
    color: fffefe
    description: This will not be worked on
  - name: backend
    color: 0e8a16
    description: Related to backend development
  - name: frontend
    color: 0e8a16
    description: Related to frontend development
  - name: security
    color: ff0000
    description: Security related issue
  - name: performance
    color: 5319e7
    description: Performance related issue
  - name: testing
    color: 1d76db
    description: Testing related issue
  - name: ci
    color: 1d76db
    description: CI/CD related issue
  - name: dependencies
    color: 0366d6
    description: Dependency updates
  - name: breaking
    color: ff0000
    description: Breaking changes
  - name: pinned
    color: 000000
    description: Pinned issue
  - name: no-issue-activity
    color: 000000
    description: No recent activity
  - name: no-pr-activity
    color: 000000
    description: No recent activity 