from setuptools import setup, find_packages

setup(
    name="sals-memory-maker",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "fastapi==0.104.1",
        "uvicorn==0.24.0",
        "sqlalchemy==2.0.23",
        "alembic==1.12.1",
        "psycopg2-binary==2.9.9",
        "python-jose[cryptography]==3.3.0",
        "passlib[bcrypt]==1.7.4",
        "python-multipart==0.0.6",
        "python-dotenv==1.0.0",
        "openai==1.3.5",
        "stripe==7.6.0",
        "pillow==10.1.0",
        "requests==2.31.0",
    ],
    extras_require={
        "dev": [
            "pytest==7.4.3",
            "pytest-cov==4.1.0",
            "black==23.10.1",
            "isort==5.12.0",
            "mypy==1.7.0",
            "flake8==6.1.0",
        ],
    },
    python_requires=">=3.9",
    author="Sal's Memory Maker",
    author_email="info@salsmemorymaker.com",
    description="A personalized book creation platform",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/sals-memory-maker",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: End Users/Desktop",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.9",
    ],
) 